export const linkTransformator = {
  'о нас': 'about',
  новости: 'news',
  карьера: 'career',
  контакты: 'contacts',
//  вконтакте: 'vkontakte',
//  инстаграм: 'instagram',
  акции: 'promo',
  игры: 'games',
  казино: 'casinos',
  промо: 'promo',
  события: 'events',
  галерея: 'gallery',
  главная: 'main',
}
