export const ACTIONS = {
  TEST: 'TEST',
  CHANGE_HEADER_NAV: 'CHANGE_HEADER_NAV',
  SAVE_NEW_TIME: 'SAVE_NEW_TIME',
  LOAD_JECKPOTS: 'LOAD_JECKPOTS',
  SAVE_JACKPOTS: 'SAVE_JACKPOTS',
  SAVE_ONE_JACKPOT: 'SAVE_ONE_JACKPOT',
  UPDATE_JACKPOTS: 'UPDATE_JACKPOTS',
  TOGGLE_MOBILE_MENU: 'TOGGLE_MOBILE_MENU',
  TOGGLE_MOBILE_MENU_DESCRIPTION_OPEN: 'TOGGLE_MOBILE_MENU_DESCRIPTION_OPEN',
  CHANGE_CASINO_DESCRIPTION_NAV: 'CHANGE_CASINO_DESCRIPTION_NAV',
  CHANGE_MENU_FULL_NAV_ITEMS_LIST: 'CHANGE_MENU_FULL_NAV_ITEMS_LIST',
}

